apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment 
spec:
  replicas: 1      
  selector:
    matchLabels:
      app: my-app     
  template:
    metadata: 
      labels:
        app: my-app   
    spec:
      containers: 
      - name: login-container
        image: vishnu4538/login:v1
        ports:
        - containerPort: 5001